# Generated by Django 6.0 on 2025-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0002_contact_delete_choice_delete_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
